#!/bin/bash
set -e
NIM_JOBS=""
while [ $# -gt 0 ]; do
    case $1 in
        -j) NIM_JOBS="NIM_PARAMS=--parallelBuild:$2"; shift 2;;
        -j*) NIM_JOBS="NIM_PARAMS=--parallelBuild:${1#-j}"; shift;;
        *) shift;;
    esac
done
if [ ! -d nimbledeps ] && [ -d ~/localdeps ]; then
    echo "Restoring nimbledeps from cache..."
    cp -a ~/localdeps nimbledeps
fi
lineflush -o output_libwaku.log env POSTGRES=1 $NIM_JOBS make libwaku
echo "Done."
